version: "3.7"

services:
    db:
        image: mysql:5.7
        container_name: db_mysql
        restart: always
        ports: 
            - 5432:5432
        environment:
            - MYSQL_USER=db_mysql
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - my-db:/var/lib/mysql
        
    app: 
        build: .
        container_name: site-eshows
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links: 
            - db_mysql
        depends_on:
            - db_mysql
        
volumes:
    db:
        driver: local